export const photoDescriptions = {
  '/assets/individuals/individual-class-3.webp': {
    fr: 'Élève jouant de la basse électrique au studio',
    en: 'Student playing electric bass in the studio',
    es: 'Alumno tocando bajo eléctrico en el estudio',
    it: 'Allievo al basso elettrico in studio',
  },
  '/assets/groups/group-class-1.webp': {
    fr: 'Enfants à la guitare et à la batterie au studio',
    en: 'Children playing guitar and drums in the studio',
    es: 'Niños tocando guitarra y batería en el estudio',
    it: 'Bambini alla chitarra e alla batteria in studio',
  },
  '/assets/groups/group-class-2.webp': {
    fr: 'Élève jouant de la basse près du piano',
    en: 'Student playing bass beside the piano',
    es: 'Alumno tocando el bajo junto al piano',
    it: 'Allievo al basso accanto al pianoforte',
  },
  '/assets/groups/group-class-3.webp': {
    fr: 'Enfants explorant les commandes d’un synthétiseur',
    en: 'Children exploring synthesiser controls',
    es: 'Niños explorando los controles de un sintetizador',
    it: 'Bambini che esplorano i comandi di un sintetizzatore',
  },
  '/assets/groups/group-class-4.webp': {
    fr: 'Enfants écrivant à la table du studio',
    en: 'Children writing at the studio desk',
    es: 'Niños escribiendo en la mesa del estudio',
    it: 'Bambini che scrivono al tavolo dello studio',
  },
  '/assets/groups/group-class-5.webp': {
    fr: 'Enfants devant l’écran d’enregistrement du studio',
    en: 'Children at the studio recording screen',
    es: 'Niños frente a la pantalla de grabación del estudio',
    it: 'Bambini davanti allo schermo di registrazione dello studio',
  },
  '/assets/groups/group-class-6.webp': {
    fr: 'Élève à la guitare électrique pendant l’atelier',
    en: 'Student on electric guitar during the workshop',
    es: 'Alumno con guitarra eléctrica durante el taller',
    it: 'Allievo alla chitarra elettrica durante il laboratorio',
  },
  '/assets/groups/group-class-7.webp': {
    fr: 'Enfants réunis avec leurs instruments dans le studio',
    en: 'Children gathered with their instruments in the studio',
    es: 'Niños reunidos con sus instrumentos en el estudio',
    it: 'Bambini riuniti con i loro strumenti in studio',
  },
  '/assets/groups/group-class-8.webp': {
    fr: 'Enfants et professeur devant les claviers du studio',
    en: 'Children and teacher at the studio keyboards',
    es: 'Niños y profesor frente a los teclados del estudio',
    it: 'Bambini e insegnante davanti alle tastiere dello studio',
  },
  '/assets/groups/group-class-9.webp': {
    fr: 'Exploration d’un contrôleur musical à plusieurs',
    en: 'Exploring a music controller together',
    es: 'Exploración compartida de un controlador musical',
    it: 'Esplorazione di un controller musicale insieme',
  },
  '/assets/groups/group-class-10.webp': {
    fr: 'Vue de l’atelier avec les élèves et leurs instruments',
    en: 'View of the workshop with students and instruments',
    es: 'Vista del taller con alumnos e instrumentos',
    it: 'Vista del laboratorio con allievi e strumenti',
  },
  '/assets/individuals/individual-class-1.webp': {
    fr: 'Élève jouant de la guitare acoustique au studio',
    en: 'Student playing acoustic guitar in the studio',
    es: 'Alumno tocando guitarra acústica en el estudio',
    it: 'Allievo alla chitarra acustica in studio',
  },
  '/assets/individuals/individual-class-2.webp': {
    fr: 'Élève et professeur travaillant la guitare ensemble',
    en: 'Student and teacher practising guitar together',
    es: 'Alumno y profesor trabajando juntos con la guitarra',
    it: 'Allievo e insegnante che suonano la chitarra insieme',
  },
  '/assets/individuals/individual-class-4.webp': {
    fr: 'Élève au clavier du piano dans le studio',
    en: 'Student at the piano keyboard in the studio',
    es: 'Alumno al teclado del piano en el estudio',
    it: 'Allievo alla tastiera del pianoforte in studio',
  },
  '/assets/individuals/individual-class-6.webp': {
    fr: 'Élève et professeur travaillant la guitare ensemble',
    en: 'Student and teacher practising guitar together',
    es: 'Alumno y profesor trabajando juntos con la guitarra',
    it: 'Allievo e insegnante che suonano la chitarra insieme',
  },
  '/assets/individuals/individual-class-7.webp': {
    fr: 'Élève jouant de la guitare acoustique au studio',
    en: 'Student playing acoustic guitar in the studio',
    es: 'Alumno tocando guitarra acústica en el estudio',
    it: 'Allievo alla chitarra acustica in studio',
  },
  '/assets/individuals/individual-class-8.webp': {
    fr: 'Exploration des commandes du synthétiseur au studio',
    en: 'Exploring synthesiser controls in the studio',
    es: 'Exploración de los controles del sintetizador en el estudio',
    it: 'Esplorazione dei comandi del sintetizzatore in studio',
  },
  '/assets/individuals/individual-class-9.webp': {
    fr: 'Élève jouant de la guitare acoustique au studio',
    en: 'Student playing acoustic guitar in the studio',
    es: 'Alumno tocando guitarra acústica en el estudio',
    it: 'Allievo alla chitarra acustica in studio',
  },
  '/assets/individuals/individual-class-12.webp': {
    fr: 'Élève jouant de la guitare acoustique au studio',
    en: 'Student playing acoustic guitar in the studio',
    es: 'Alumno tocando guitarra acústica en el estudio',
    it: 'Allievo alla chitarra acustica in studio',
  },
  '/assets/individuals/individual-class-13.webp': {
    fr: 'Élève au clavier du piano dans le studio',
    en: 'Student at the piano keyboard in the studio',
    es: 'Alumno al teclado del piano en el estudio',
    it: 'Allievo alla tastiera del pianoforte in studio',
  },
  '/assets/individuals/individual-class-14.webp': {
    fr: 'Élève jouant de la guitare électrique au studio',
    en: 'Student playing electric guitar in the studio',
    es: 'Alumno tocando guitarra eléctrica en el estudio',
    it: 'Allievo alla chitarra elettrica in studio',
  },
  '/assets/individuals/individual-class-17.webp': {
    fr: 'Élève jouant de la guitare acoustique au studio',
    en: 'Student playing acoustic guitar in the studio',
    es: 'Alumno tocando guitarra acústica en el estudio',
    it: 'Allievo alla chitarra acustica in studio',
  },
};
